output {
  if "weather_parsed" in [tags] {
    elasticsearch {
      hosts    => ["http://192.168.122.1:9200"]
      index    => "weather-%{[location]}-%{+YYYY.MM.dd}"
      action   => "index"
    }
  }
}
