# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class OrchestratorHostInfo(BaseModel):
    """
    OrchestratorHostInfo
    """  # noqa: E501

    active_sandboxes: Optional[StrictInt] = None
    available_cpus: Optional[StrictInt] = None
    available_disk_mb: Optional[StrictInt] = None
    available_memory_mb: Optional[StrictInt] = None
    base_images: Optional[List[StrictStr]] = None
    host_id: Optional[StrictStr] = None
    hostname: Optional[StrictStr] = None
    last_heartbeat: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "active_sandboxes",
        "available_cpus",
        "available_disk_mb",
        "available_memory_mb",
        "base_images",
        "host_id",
        "hostname",
        "last_heartbeat",
        "status",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrchestratorHostInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrchestratorHostInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "active_sandboxes": obj.get("active_sandboxes"),
                "available_cpus": obj.get("available_cpus"),
                "available_disk_mb": obj.get("available_disk_mb"),
                "available_memory_mb": obj.get("available_memory_mb"),
                "base_images": obj.get("base_images"),
                "host_id": obj.get("host_id"),
                "hostname": obj.get("hostname"),
                "last_heartbeat": obj.get("last_heartbeat"),
                "status": obj.get("status"),
            }
        )
        return _obj
