# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self

from fluid.models.store_sandbox_state import StoreSandboxState


class StoreSandbox(BaseModel):
    """
    StoreSandbox
    """  # noqa: E501

    agent_id: Optional[StrictStr] = None
    base_image: Optional[StrictStr] = None
    bridge: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    deleted_at: Optional[StrictStr] = None
    host_id: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    ip_address: Optional[StrictStr] = None
    mac_address: Optional[StrictStr] = None
    memory_mb: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    org_id: Optional[StrictStr] = None
    source_vm: Optional[StrictStr] = None
    state: Optional[StoreSandboxState] = None
    tap_device: Optional[StrictStr] = None
    ttl_seconds: Optional[StrictInt] = None
    updated_at: Optional[StrictStr] = None
    vcpus: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = [
        "agent_id",
        "base_image",
        "bridge",
        "created_at",
        "deleted_at",
        "host_id",
        "id",
        "ip_address",
        "mac_address",
        "memory_mb",
        "name",
        "org_id",
        "source_vm",
        "state",
        "tap_device",
        "ttl_seconds",
        "updated_at",
        "vcpus",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoreSandbox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoreSandbox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "agent_id": obj.get("agent_id"),
                "base_image": obj.get("base_image"),
                "bridge": obj.get("bridge"),
                "created_at": obj.get("created_at"),
                "deleted_at": obj.get("deleted_at"),
                "host_id": obj.get("host_id"),
                "id": obj.get("id"),
                "ip_address": obj.get("ip_address"),
                "mac_address": obj.get("mac_address"),
                "memory_mb": obj.get("memory_mb"),
                "name": obj.get("name"),
                "org_id": obj.get("org_id"),
                "source_vm": obj.get("source_vm"),
                "state": obj.get("state"),
                "tap_device": obj.get("tap_device"),
                "ttl_seconds": obj.get("ttl_seconds"),
                "updated_at": obj.get("updated_at"),
                "vcpus": obj.get("vcpus"),
            }
        )
        return _obj
