# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_rest_list_sandboxes_response import \
    GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse


class TestGithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse:
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse(
                sandboxes = [
                    {"base_image":"base_image","agent_id":"agent_id","updated_at":"updated_at","job_id":"job_id","ttl_seconds":0,"created_at":"created_at","sandbox_name":"sandbox_name","id":"id","ip_address":"ip_address","state":"state","network":"network"}
                    ],
                total = 56
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
