# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_get(self) -> None:
        """Test case for orgs_get

        List organizations
        """
        pass

    def test_orgs_post(self) -> None:
        """Test case for orgs_post

        Create organization
        """
        pass

    def test_orgs_slug_delete(self) -> None:
        """Test case for orgs_slug_delete

        Delete organization
        """
        pass

    def test_orgs_slug_get(self) -> None:
        """Test case for orgs_slug_get

        Get organization
        """
        pass

    def test_orgs_slug_patch(self) -> None:
        """Test case for orgs_slug_patch

        Update organization
        """
        pass


if __name__ == "__main__":
    unittest.main()
