# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_rest_run_command_response import \
    GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse


class TestGithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse:
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse(
                command = {"metadata":{"redacted":{"key":"redacted"},"work_dir":"work_dir","user":"user","timeout":6},"stdout":"stdout","env_json":"env_json","exit_code":0,"sandbox_id":"sandbox_id","started_at":"started_at","id":"id","stderr":"stderr","command":"command","ended_at":"ended_at"}
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestRunCommandResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
