# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_ansible_job_status import \
    GithubComAspectrrFluidShFluidRemoteInternalAnsibleJobStatus


class TestGithubComAspectrrFluidShFluidRemoteInternalAnsibleJobStatus(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalAnsibleJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComAspectrrFluidShFluidRemoteInternalAnsibleJobStatus(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalAnsibleJobStatus"""
        # inst = GithubComAspectrrFluidShFluidRemoteInternalAnsibleJobStatus()


if __name__ == "__main__":
    unittest.main()
