# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.billing_api import BillingApi


class TestBillingApi(unittest.TestCase):
    """BillingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingApi()

    def tearDown(self) -> None:
        pass

    def test_billing_calculator_post(self) -> None:
        """Test case for billing_calculator_post

        Pricing calculator
        """
        pass

    def test_orgs_slug_billing_get(self) -> None:
        """Test case for orgs_slug_billing_get

        Get billing info
        """
        pass

    def test_orgs_slug_billing_portal_post(self) -> None:
        """Test case for orgs_slug_billing_portal_post

        Billing portal
        """
        pass

    def test_orgs_slug_billing_subscribe_post(self) -> None:
        """Test case for orgs_slug_billing_subscribe_post

        Subscribe
        """
        pass

    def test_orgs_slug_billing_usage_get(self) -> None:
        """Test case for orgs_slug_billing_usage_get

        Get usage
        """
        pass

    def test_webhooks_stripe_post(self) -> None:
        """Test case for webhooks_stripe_post

        Stripe webhook
        """
        pass


if __name__ == "__main__":
    unittest.main()
