# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.store_sandbox_state import StoreSandboxState


class TestStoreSandboxState(unittest.TestCase):
    """StoreSandboxState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreSandboxState(self):
        """Test StoreSandboxState"""
        # inst = StoreSandboxState()


if __name__ == "__main__":
    unittest.main()
