# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.source_vms_api import SourceVMsApi


class TestSourceVMsApi(unittest.TestCase):
    """SourceVMsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SourceVMsApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_slug_sources_vm_prepare_post(self) -> None:
        """Test case for orgs_slug_sources_vm_prepare_post

        Prepare source VM
        """
        pass

    def test_orgs_slug_sources_vm_read_post(self) -> None:
        """Test case for orgs_slug_sources_vm_read_post

        Read source file
        """
        pass

    def test_orgs_slug_sources_vm_run_post(self) -> None:
        """Test case for orgs_slug_sources_vm_run_post

        Run source command
        """
        pass

    def test_orgs_slug_vms_get(self) -> None:
        """Test case for orgs_slug_vms_get

        List source VMs
        """
        pass


if __name__ == "__main__":
    unittest.main()
