# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_ansible_get_playbook_response import \
    GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse


class TestGithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse:
        """Test GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse(
                playbook = {"file_path":"file_path","updated_at":"updated_at","hosts":"hosts","name":"name","created_at":"created_at","id":"id","become":true},
                tasks = [
                    {"module":"module","name":"name","created_at":"created_at","id":"id","position":0,"params":"{}","playbook_id":"playbook_id"}
                    ]
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalAnsibleGetPlaybookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
