# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.rest_login_request import RestLoginRequest


class TestRestLoginRequest(unittest.TestCase):
    """RestLoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestLoginRequest:
        """Test RestLoginRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RestLoginRequest`
        """
        model = RestLoginRequest()
        if include_optional:
            return RestLoginRequest(
                email = '',
                password = ''
            )
        else:
            return RestLoginRequest(
        )
        """

    def testRestLoginRequest(self):
        """Test RestLoginRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
