# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store_sandbox import \
    GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox


class TestGithubComAspectrrFluidShFluidRemoteInternalStoreSandbox(unittest.TestCase):
    """GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox:
        """Test GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox(
                agent_id = '',
                base_image = '',
                created_at = '',
                deleted_at = '',
                host_address = '',
                host_name = '',
                id = '',
                ip_address = '',
                job_id = '',
                network = '',
                sandbox_name = '',
                state = 'CREATED',
                ttl_seconds = 56,
                updated_at = ''
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalStoreSandbox(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
