# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_rest_request_access_response import \
    GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse


class TestGithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse:
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse(
                certificate = '',
                certificate_id = '',
                connect_command = '',
                instructions = '',
                ssh_port = 56,
                ttl_seconds = 56,
                username = '',
                valid_until = '',
                vm_ip_address = ''
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
