# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_github_callback_get(self) -> None:
        """Test case for auth_github_callback_get

        GitHub OAuth callback
        """
        pass

    def test_auth_github_get(self) -> None:
        """Test case for auth_github_get

        GitHub OAuth login
        """
        pass

    def test_auth_google_callback_get(self) -> None:
        """Test case for auth_google_callback_get

        Google OAuth callback
        """
        pass

    def test_auth_google_get(self) -> None:
        """Test case for auth_google_get

        Google OAuth login
        """
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        Log in
        """
        pass

    def test_auth_logout_post(self) -> None:
        """Test case for auth_logout_post

        Log out
        """
        pass

    def test_auth_me_get(self) -> None:
        """Test case for auth_me_get

        Get current user
        """
        pass

    def test_auth_register_post(self) -> None:
        """Test case for auth_register_post

        Register a new user
        """
        pass


if __name__ == "__main__":
    unittest.main()
