# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_ansible_job import \
    GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob


class TestGithubComAspectrrFluidShFluidRemoteInternalAnsibleJob(unittest.TestCase):
    """GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob:
        """Test GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob(
                check = True,
                id = '',
                playbook = '',
                status = 'pending',
                vm_name = ''
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalAnsibleJob(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalAnsibleJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
