# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_rest_list_sandbox_commands_response import \
    GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse


class TestGithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse:
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse(
                commands = [
                    {"metadata":{"redacted":{"key":"redacted"},"work_dir":"work_dir","user":"user","timeout":6},"stdout":"stdout","env_json":"env_json","exit_code":0,"sandbox_id":"sandbox_id","started_at":"started_at","id":"id","stderr":"stderr","command":"command","ended_at":"ended_at"}
                    ],
                total = 56
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse(
        self,
    ):
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestListSandboxCommandsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
