# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store_diff import \
    GithubComAspectrrFluidShFluidRemoteInternalStoreDiff


class TestGithubComAspectrrFluidShFluidRemoteInternalStoreDiff(unittest.TestCase):
    """GithubComAspectrrFluidShFluidRemoteInternalStoreDiff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalStoreDiff:
        """Test GithubComAspectrrFluidShFluidRemoteInternalStoreDiff
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalStoreDiff`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalStoreDiff()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalStoreDiff(
                created_at = '',
                diff_json = fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store/change_diff.github_com_aspectrr_fluid_sh_fluid-remote_internal_store.ChangeDiff(
                    commands_run = [
                        fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store/command_summary.github_com_aspectrr_fluid_sh_fluid-remote_internal_store.CommandSummary(
                            at = '', 
                            cmd = '', 
                            exit_code = 56, )
                        ], 
                    files_added = [
                        ''
                        ], 
                    files_modified = [
                        ''
                        ], 
                    files_removed = [
                        ''
                        ], 
                    packages_added = [
                        fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store/package_info.github_com_aspectrr_fluid_sh_fluid-remote_internal_store.PackageInfo(
                            name = '', 
                            version = '', )
                        ], 
                    packages_removed = [
                        fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store/package_info.github_com_aspectrr_fluid_sh_fluid-remote_internal_store.PackageInfo(
                            name = '', 
                            version = '', )
                        ], 
                    services_changed = [
                        fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store/service_change.github_com_aspectrr_fluid_sh_fluid-remote_internal_store.ServiceChange(
                            enabled = True, 
                            name = '', 
                            state = '', )
                        ], ),
                from_snapshot = '',
                id = '',
                sandbox_id = '',
                to_snapshot = ''
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalStoreDiff(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalStoreDiff(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalStoreDiff"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
