# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.orchestrator_snapshot_request import \
    OrchestratorSnapshotRequest


class TestOrchestratorSnapshotRequest(unittest.TestCase):
    """OrchestratorSnapshotRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrchestratorSnapshotRequest:
        """Test OrchestratorSnapshotRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrchestratorSnapshotRequest`
        """
        model = OrchestratorSnapshotRequest()
        if include_optional:
            return OrchestratorSnapshotRequest(
                name = ''
            )
        else:
            return OrchestratorSnapshotRequest(
        )
        """

    def testOrchestratorSnapshotRequest(self):
        """Test OrchestratorSnapshotRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
