# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_rest_publish_response import \
    GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse


class TestGithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse:
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse(
                message = '',
                note = ''
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestPublishResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
