# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_rest_request_access_request import \
    GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest


class TestGithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest(
    unittest.TestCase
):
    """GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest:
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest`
        """
        model = GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest()
        if include_optional:
            return GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest(
                public_key = '',
                sandbox_id = '',
                ttl_minutes = 56,
                user_id = ''
            )
        else:
            return GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest(
        )
        """

    def testGithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest(self):
        """Test GithubComAspectrrFluidShFluidRemoteInternalRestRequestAccessRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
