# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.host_tokens_api import HostTokensApi


class TestHostTokensApi(unittest.TestCase):
    """HostTokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HostTokensApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_slug_hosts_tokens_get(self) -> None:
        """Test case for orgs_slug_hosts_tokens_get

        List host tokens
        """
        pass

    def test_orgs_slug_hosts_tokens_post(self) -> None:
        """Test case for orgs_slug_hosts_tokens_post

        Create host token
        """
        pass

    def test_orgs_slug_hosts_tokens_token_id_delete(self) -> None:
        """Test case for orgs_slug_hosts_tokens_token_id_delete

        Delete host token
        """
        pass


if __name__ == "__main__":
    unittest.main()
