# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.orchestrator_host_info import OrchestratorHostInfo


class TestOrchestratorHostInfo(unittest.TestCase):
    """OrchestratorHostInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrchestratorHostInfo:
        """Test OrchestratorHostInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrchestratorHostInfo`
        """
        model = OrchestratorHostInfo()
        if include_optional:
            return OrchestratorHostInfo(
                active_sandboxes = 56,
                available_cpus = 56,
                available_disk_mb = 56,
                available_memory_mb = 56,
                base_images = [
                    ''
                    ],
                host_id = '',
                hostname = '',
                last_heartbeat = '',
                status = ''
            )
        else:
            return OrchestratorHostInfo(
        )
        """

    def testOrchestratorHostInfo(self):
        """Test OrchestratorHostInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
