# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.rest_calculator_request import RestCalculatorRequest


class TestRestCalculatorRequest(unittest.TestCase):
    """RestCalculatorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestCalculatorRequest:
        """Test RestCalculatorRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RestCalculatorRequest`
        """
        model = RestCalculatorRequest()
        if include_optional:
            return RestCalculatorRequest(
                agent_hosts = 56,
                concurrent_sandboxes = 56,
                hours_per_month = 1.337,
                source_vms = 56
            )
        else:
            return RestCalculatorRequest(
        )
        """

    def testRestCalculatorRequest(self):
        """Test RestCalculatorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
