# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.sandboxes_api import SandboxesApi


class TestSandboxesApi(unittest.TestCase):
    """SandboxesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SandboxesApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_slug_sandboxes_get(self) -> None:
        """Test case for orgs_slug_sandboxes_get

        List sandboxes
        """
        pass

    def test_orgs_slug_sandboxes_post(self) -> None:
        """Test case for orgs_slug_sandboxes_post

        Create sandbox
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_commands_get(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_commands_get

        List commands
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_delete(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_delete

        Destroy sandbox
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_get(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_get

        Get sandbox
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_run_post(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_run_post

        Run command
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_snapshot_post(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_snapshot_post

        Create snapshot
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_start_post(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_start_post

        Start sandbox
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_id_stop_post(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_id_stop_post

        Stop sandbox
        """
        pass

    def test_orgs_slug_sandboxes_sandbox_idip_get(self) -> None:
        """Test case for orgs_slug_sandboxes_sandbox_idip_get

        Get sandbox IP
        """
        pass


if __name__ == "__main__":
    unittest.main()
