# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.hosts_api import HostsApi


class TestHostsApi(unittest.TestCase):
    """HostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HostsApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_slug_hosts_get(self) -> None:
        """Test case for orgs_slug_hosts_get

        List hosts
        """
        pass

    def test_orgs_slug_hosts_host_id_get(self) -> None:
        """Test case for orgs_slug_hosts_host_id_get

        Get host
        """
        pass


if __name__ == "__main__":
    unittest.main()
