# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.orchestrator_create_sandbox_request import \
    OrchestratorCreateSandboxRequest


class TestOrchestratorCreateSandboxRequest(unittest.TestCase):
    """OrchestratorCreateSandboxRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrchestratorCreateSandboxRequest:
        """Test OrchestratorCreateSandboxRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrchestratorCreateSandboxRequest`
        """
        model = OrchestratorCreateSandboxRequest()
        if include_optional:
            return OrchestratorCreateSandboxRequest(
                agent_id = '',
                base_image = '',
                memory_mb = 56,
                name = '',
                network = '',
                org_id = '',
                source_vm = '',
                ttl_seconds = 56,
                vcpus = 56
            )
        else:
            return OrchestratorCreateSandboxRequest(
        )
        """

    def testOrchestratorCreateSandboxRequest(self):
        """Test OrchestratorCreateSandboxRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
