# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.rest_auth_response import RestAuthResponse


class TestRestAuthResponse(unittest.TestCase):
    """RestAuthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestAuthResponse:
        """Test RestAuthResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RestAuthResponse`
        """
        model = RestAuthResponse()
        if include_optional:
            return RestAuthResponse(
                user = {"email_verified":true,"avatar_url":"avatar_url","id":"id","display_name":"display_name","email":"email"}
            )
        else:
            return RestAuthResponse(
        )
        """

    def testRestAuthResponse(self):
        """Test RestAuthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
