# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.rest_billing_response import RestBillingResponse


class TestRestBillingResponse(unittest.TestCase):
    """RestBillingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestBillingResponse:
        """Test RestBillingResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RestBillingResponse`
        """
        model = RestBillingResponse()
        if include_optional:
            return RestBillingResponse(
                free_tier = {"max_agent_hosts":0,"max_concurrent_sandboxes":6,"max_source_vms":1},
                plan = '',
                status = '',
                usage = {"agent_hosts":5.962133916683182,"sandbox_hours":5.637376656633329,"source_vms":2.3021358869347655}
            )
        else:
            return RestBillingResponse(
        )
        """

    def testRestBillingResponse(self):
        """Test RestBillingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
