# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.orchestrator_snapshot_response import \
    OrchestratorSnapshotResponse


class TestOrchestratorSnapshotResponse(unittest.TestCase):
    """OrchestratorSnapshotResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrchestratorSnapshotResponse:
        """Test OrchestratorSnapshotResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrchestratorSnapshotResponse`
        """
        model = OrchestratorSnapshotResponse()
        if include_optional:
            return OrchestratorSnapshotResponse(
                created_at = '',
                sandbox_id = '',
                snapshot_id = '',
                snapshot_name = ''
            )
        else:
            return OrchestratorSnapshotResponse(
        )
        """

    def testOrchestratorSnapshotResponse(self):
        """Test OrchestratorSnapshotResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
