# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.api.members_api import MembersApi


class TestMembersApi(unittest.TestCase):
    """MembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembersApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_slug_members_get(self) -> None:
        """Test case for orgs_slug_members_get

        List members
        """
        pass

    def test_orgs_slug_members_member_id_delete(self) -> None:
        """Test case for orgs_slug_members_member_id_delete

        Remove member
        """
        pass

    def test_orgs_slug_members_post(self) -> None:
        """Test case for orgs_slug_members_post

        Add member
        """
        pass


if __name__ == "__main__":
    unittest.main()
