# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.store_sandbox import StoreSandbox


class TestStoreSandbox(unittest.TestCase):
    """StoreSandbox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreSandbox:
        """Test StoreSandbox
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `StoreSandbox`
        """
        model = StoreSandbox()
        if include_optional:
            return StoreSandbox(
                agent_id = '',
                base_image = '',
                bridge = '',
                created_at = '',
                deleted_at = '',
                host_id = '',
                id = '',
                ip_address = '',
                mac_address = '',
                memory_mb = 56,
                name = '',
                org_id = '',
                source_vm = '',
                state = 'CREATING',
                tap_device = '',
                ttl_seconds = 56,
                updated_at = '',
                vcpus = 56
            )
        else:
            return StoreSandbox(
        )
        """

    def testStoreSandbox(self):
        """Test StoreSandbox"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
