# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.rest_free_tier_info import RestFreeTierInfo


class TestRestFreeTierInfo(unittest.TestCase):
    """RestFreeTierInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestFreeTierInfo:
        """Test RestFreeTierInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RestFreeTierInfo`
        """
        model = RestFreeTierInfo()
        if include_optional:
            return RestFreeTierInfo(
                max_agent_hosts = 56,
                max_concurrent_sandboxes = 56,
                max_source_vms = 56
            )
        else:
            return RestFreeTierInfo(
        )
        """

    def testRestFreeTierInfo(self):
        """Test RestFreeTierInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
