# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fluid.models.rest_add_member_request import RestAddMemberRequest


class TestRestAddMemberRequest(unittest.TestCase):
    """RestAddMemberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestAddMemberRequest:
        """Test RestAddMemberRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RestAddMemberRequest`
        """
        model = RestAddMemberRequest()
        if include_optional:
            return RestAddMemberRequest(
                email = '',
                role = ''
            )
        else:
            return RestAddMemberRequest(
        )
        """

    def testRestAddMemberRequest(self):
        """Test RestAddMemberRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
