# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from fluid.models.github_com_aspectrr_fluid_sh_fluid_remote_internal_store_sandbox_state import \
    GithubComAspectrrFluidShFluidRemoteInternalStoreSandboxState


class GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox(BaseModel):
    """
    GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox
    """  # noqa: E501

    agent_id: Optional[StrictStr] = Field(
        default=None, description="requesting agent identity"
    )
    base_image: Optional[StrictStr] = Field(
        default=None, description="base qcow2 filename"
    )
    created_at: Optional[StrictStr] = Field(default=None, description="Metadata")
    deleted_at: Optional[StrictStr] = None
    host_address: Optional[StrictStr] = Field(
        default=None, description="IP or hostname of the libvirt host"
    )
    host_name: Optional[StrictStr] = Field(
        default=None,
        description="Multi-host support: identifies which libvirt host this sandbox runs on",
    )
    id: Optional[StrictStr] = Field(default=None, description='e.g., "SBX-0001"')
    ip_address: Optional[StrictStr] = Field(
        default=None, description="discovered IP (if any)"
    )
    job_id: Optional[StrictStr] = Field(
        default=None, description="correlation id for the end-to-end change set"
    )
    network: Optional[StrictStr] = Field(
        default=None, description="libvirt network name"
    )
    sandbox_name: Optional[StrictStr] = Field(
        default=None, description="libvirt domain name"
    )
    state: Optional[GithubComAspectrrFluidShFluidRemoteInternalStoreSandboxState] = None
    ttl_seconds: Optional[StrictInt] = Field(
        default=None, description="optional TTL for auto GC"
    )
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "agent_id",
        "base_image",
        "created_at",
        "deleted_at",
        "host_address",
        "host_name",
        "id",
        "ip_address",
        "job_id",
        "network",
        "sandbox_name",
        "state",
        "ttl_seconds",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComAspectrrFluidShFluidRemoteInternalStoreSandbox from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "agent_id": obj.get("agent_id"),
                "base_image": obj.get("base_image"),
                "created_at": obj.get("created_at"),
                "deleted_at": obj.get("deleted_at"),
                "host_address": obj.get("host_address"),
                "host_name": obj.get("host_name"),
                "id": obj.get("id"),
                "ip_address": obj.get("ip_address"),
                "job_id": obj.get("job_id"),
                "network": obj.get("network"),
                "sandbox_name": obj.get("sandbox_name"),
                "state": obj.get("state"),
                "ttl_seconds": obj.get("ttl_seconds"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
