# coding: utf-8

"""
    fluid-remote API

    API for managing AI Agent VM sandboxes using libvirt

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class GithubComAspectrrFluidShFluidRemoteInternalStoreSnapshotKind(str, Enum):
    """
    GithubComAspectrrFluidShFluidRemoteInternalStoreSnapshotKind
    """

    """
    allowed enum values
    """
    SnapshotKindInternal = "INTERNAL"
    SnapshotKindExternal = "EXTERNAL"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GithubComAspectrrFluidShFluidRemoteInternalStoreSnapshotKind from a JSON string"""
        return cls(json.loads(json_str))
