# coding: utf-8

"""
    Fluid API

    API for managing sandboxes, organizations, billing, and hosts

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class StoreCommand(BaseModel):
    """
    StoreCommand
    """  # noqa: E501

    command: Optional[StrictStr] = None
    duration_ms: Optional[StrictInt] = None
    ended_at: Optional[StrictStr] = None
    exit_code: Optional[StrictInt] = None
    id: Optional[StrictStr] = None
    sandbox_id: Optional[StrictStr] = None
    started_at: Optional[StrictStr] = None
    stderr: Optional[StrictStr] = None
    stdout: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "command",
        "duration_ms",
        "ended_at",
        "exit_code",
        "id",
        "sandbox_id",
        "started_at",
        "stderr",
        "stdout",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoreCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoreCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "command": obj.get("command"),
                "duration_ms": obj.get("duration_ms"),
                "ended_at": obj.get("ended_at"),
                "exit_code": obj.get("exit_code"),
                "id": obj.get("id"),
                "sandbox_id": obj.get("sandbox_id"),
                "started_at": obj.get("started_at"),
                "stderr": obj.get("stderr"),
                "stdout": obj.get("stdout"),
            }
        )
        return _obj
