/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DocsUpgradeRouteImport } from './routes/docs/upgrade'
import { Route as DocsSandboxesRouteImport } from './routes/docs/sandboxes'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsMcpRouteImport } from './routes/docs/mcp'
import { Route as DocsLocalSetupRouteImport } from './routes/docs/local-setup'
import { Route as DocsDaemonRouteImport } from './routes/docs/daemon'
import { Route as DocsCliReferenceRouteImport } from './routes/docs/cli-reference'
import { Route as DocsArchitectureRouteImport } from './routes/docs/architecture'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app/settings/organization'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsHostsRouteImport } from './routes/_app/settings/hosts'
import { Route as AppBillingCalculatorRouteImport } from './routes/_app/billing/calculator'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DocsUpgradeRoute = DocsUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSandboxesRoute = DocsSandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLocalSetupRoute = DocsLocalSetupRouteImport.update({
  id: '/local-setup',
  path: '/local-setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDaemonRoute = DocsDaemonRouteImport.update({
  id: '/daemon',
  path: '/daemon',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliReferenceRoute = DocsCliReferenceRouteImport.update({
  id: '/cli-reference',
  path: '/cli-reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsHostsRoute = AppSettingsHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppBillingCalculatorRoute = AppBillingCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/docs': typeof DocsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/cli-reference': typeof DocsCliReferenceRoute
  '/docs/daemon': typeof DocsDaemonRoute
  '/docs/local-setup': typeof DocsLocalSetupRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/sandboxes': typeof DocsSandboxesRoute
  '/docs/upgrade': typeof DocsUpgradeRoute
  '/': typeof PublicIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/billing/calculator': typeof AppBillingCalculatorRoute
  '/settings/hosts': typeof AppSettingsHostsRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/billing/': typeof AppBillingIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/blog': typeof PublicBlogIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/cli-reference': typeof DocsCliReferenceRoute
  '/docs/daemon': typeof DocsDaemonRoute
  '/docs/local-setup': typeof DocsLocalSetupRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/sandboxes': typeof DocsSandboxesRoute
  '/docs/upgrade': typeof DocsUpgradeRoute
  '/': typeof PublicIndexRoute
  '/docs': typeof DocsIndexRoute
  '/billing/calculator': typeof AppBillingCalculatorRoute
  '/settings/hosts': typeof AppSettingsHostsRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/billing': typeof AppBillingIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/blog': typeof PublicBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/cli-reference': typeof DocsCliReferenceRoute
  '/docs/daemon': typeof DocsDaemonRoute
  '/docs/local-setup': typeof DocsLocalSetupRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/sandboxes': typeof DocsSandboxesRoute
  '/docs/upgrade': typeof DocsUpgradeRoute
  '/_public/': typeof PublicIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_app/billing/calculator': typeof AppBillingCalculatorRoute
  '/_app/settings/hosts': typeof AppSettingsHostsRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/docs'
    | '/onboarding'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/register'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/cli-reference'
    | '/docs/daemon'
    | '/docs/local-setup'
    | '/docs/mcp'
    | '/docs/quickstart'
    | '/docs/sandboxes'
    | '/docs/upgrade'
    | '/'
    | '/docs/'
    | '/billing/calculator'
    | '/settings/hosts'
    | '/settings/members'
    | '/settings/organization'
    | '/blog/$slug'
    | '/billing/'
    | '/settings/'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/cli-reference'
    | '/docs/daemon'
    | '/docs/local-setup'
    | '/docs/mcp'
    | '/docs/quickstart'
    | '/docs/sandboxes'
    | '/docs/upgrade'
    | '/'
    | '/docs'
    | '/billing/calculator'
    | '/settings/hosts'
    | '/settings/members'
    | '/settings/organization'
    | '/blog/$slug'
    | '/billing'
    | '/settings'
    | '/blog'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_public'
    | '/docs'
    | '/onboarding'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/cli-reference'
    | '/docs/daemon'
    | '/docs/local-setup'
    | '/docs/mcp'
    | '/docs/quickstart'
    | '/docs/sandboxes'
    | '/docs/upgrade'
    | '/_public/'
    | '/docs/'
    | '/_app/billing/calculator'
    | '/_app/settings/hosts'
    | '/_app/settings/members'
    | '/_app/settings/organization'
    | '/_public/blog/$slug'
    | '/_app/billing/'
    | '/_app/settings/'
    | '/_public/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/docs/upgrade': {
      id: '/docs/upgrade'
      path: '/upgrade'
      fullPath: '/docs/upgrade'
      preLoaderRoute: typeof DocsUpgradeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sandboxes': {
      id: '/docs/sandboxes'
      path: '/sandboxes'
      fullPath: '/docs/sandboxes'
      preLoaderRoute: typeof DocsSandboxesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/local-setup': {
      id: '/docs/local-setup'
      path: '/local-setup'
      fullPath: '/docs/local-setup'
      preLoaderRoute: typeof DocsLocalSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/daemon': {
      id: '/docs/daemon'
      path: '/daemon'
      fullPath: '/docs/daemon'
      preLoaderRoute: typeof DocsDaemonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli-reference': {
      id: '/docs/cli-reference'
      path: '/cli-reference'
      fullPath: '/docs/cli-reference'
      preLoaderRoute: typeof DocsCliReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/hosts': {
      id: '/_app/settings/hosts'
      path: '/hosts'
      fullPath: '/settings/hosts'
      preLoaderRoute: typeof AppSettingsHostsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/billing/calculator': {
      id: '/_app/billing/calculator'
      path: '/calculator'
      fullPath: '/billing/calculator'
      preLoaderRoute: typeof AppBillingCalculatorRouteImport
      parentRoute: typeof AppBillingRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingCalculatorRoute: typeof AppBillingCalculatorRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingCalculatorRoute: AppBillingCalculatorRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsHostsRoute: typeof AppSettingsHostsRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsHostsRoute: AppSettingsHostsRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsCliReferenceRoute: typeof DocsCliReferenceRoute
  DocsDaemonRoute: typeof DocsDaemonRoute
  DocsLocalSetupRoute: typeof DocsLocalSetupRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsSandboxesRoute: typeof DocsSandboxesRoute
  DocsUpgradeRoute: typeof DocsUpgradeRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsCliReferenceRoute: DocsCliReferenceRoute,
  DocsDaemonRoute: DocsDaemonRoute,
  DocsLocalSetupRoute: DocsLocalSetupRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsSandboxesRoute: DocsSandboxesRoute,
  DocsUpgradeRoute: DocsUpgradeRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
