input {
  kafka {
    bootstrap_servers => "127.0.0.1:9092"
    topics            => ["new-york", "chicago", "sf", "la", "indy"]
    group_id          => "logstash-weather-consumer"
    auto_offset_reset => "earliest"
    codec             => plain { charset => "UTF-8" }
    consumer_threads  => 2
    decorate_events   => false
  }
}
