filter {
  grok {
    match => { "message" => "%{WORD:station_id}\t%{DATA:location}\t%{BASE10NUM:latitude}\t%{BASE10NUM:longitude}\t%{DATA:event_timestamp}\t%{BASE10NUM:temperature}\t%{BASE10NUM:feels_like}\t%{INT:humidity}\t%{BASE10NUM:dew_point}\t%{BASE10NUM:wind_speed}\t%{INT:wind_dir}\t%{GREEDYDATA:wind_gusts}" }
    add_tag => ["tsv_weather", "weather_parsed"]
  }
}
