filter {
  if "tsv_weather" in [tags] {
    ruby {
      code => "
        cols = event.get('message')
        if cols.is_a?(Array) && cols.length == 20
          event.set('station_id',       cols[0])
          event.set('location',         cols[1])
          event.set('latitude',         cols[2])
          event.set('longitude',        cols[3])
          event.set('event_timestamp',  cols[4])
          event.set('temperature',      cols[5])
          event.set('feels_like',       cols[6])
          event.set('humidity',         cols[7])
          event.set('dew_point',        cols[8])
          event.set('wind_speed',       cols[9])
          event.set('wind_dir',         cols[10])
          event.set('wind_gusts',       cols[11])
          event.set('pressure',         cols[12])
          event.set('cloud_cover',      cols[13])
          event.set('visibility',       cols[14])
          event.set('uv_index',         cols[15])
          event.set('precipitation',    cols[16])
          event.set('weather_code',     cols[17])
          event.set('is_day',           cols[18])
          event.set('soil_temperature', cols[19])
          event.tag('weather_parsed')
        else
          event.tag('_tsvparsefailure')
        end
        event.remove('[message]')
      "
    }
  }
}
