filter {
  if "weather_parsed" in [tags] {
    date {
      match    => ["event_timestamp", "yyyy-MM-dd'T'HH:mm:ss'Z'", "ISO8601"]
      target   => "@timestamp"
      timezone => "%{station_timezone}"
    }
    mutate {
      remove_field => ["event_timestamp"]
    }
  }
}
